import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} common-class`}>
      <div className="mt-5 mb-[120px]">
         <Header/>
      </div>
        {children}
      </body>
    </html>
  );
}
