import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import React, { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Healthcare",
  description: "Generated by create next app",
  icon: "/logo.png", // Assuming your logo is located at public/logo.png
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${inter.className} common-class`}>
        <div className="my-5">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;